### ISSUE TITLE
T-010: Return proper response JSON format from the API

### ISSUE THREAD

**Issue by ak2403** [mshrestha8080/ToDoAPI#10]

**Comment by mshrestha8080** [comment]
<img width="908" alt="Screen Shot 2022-02-21 at 10 53 12 am" src="https://user-images.githubusercontent.com/99297781/154870137-55d95ab8-9b3c-4213-a92b-be92187e3501.png">

Is this is the proper response JSON format? @ak2403

**Comment by mshrestha8080** [comment]
Response in JSON format from API call has been fixed
